name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Navigate to project directory or create it
            cd /home/${{ secrets.VPS_USER }} || cd ~
            
            # Clone or pull repository
            if [ -d "ai_demo" ]; then
              cd ai_demo
              git pull origin main
            else
              git clone ${{ secrets.REPO_URL }} ai_demo
              cd ai_demo
            fi
            
            # Stop and remove existing containers
            docker-compose down || true
            
            # Build and start containers
            docker-compose up -d --build
            
            # Clean up old images
            docker image prune -f
            
            echo "Deployment completed successfully!"
